version: "2.1"

services:
  node:
    container_name: angularcontainer
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 4201:4201
    volumes:
      - "./:/var/www/html"
    working_dir: /var/www/html
    command: ng serve --host 0.0.0.0 --poll=2000 --port 4201

