version: "3.8"

services:
  node:
    container_name: angularcontainer
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4201:443"
    volumes:
      - "./:/var/www/html"
      - "./ssl:/certs"  # Mount the certificates
    working_dir: /var/www/html
    command: ng serve --host 0.0.0.0 --poll=2000 --port 443 --ssl true --ssl-key /certs/server.key --ssl-cert /certs/server.crt
