version: '3.8'

services:
  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/symfony
    environment:
      DATABASE_URL: mysql://zm_32:zm_32@database:3306/zm_32
    networks:
      - symfony-angular-network
    depends_on:
      database:
        condition: service_healthy
    entrypoint: /usr/local/bin/entrypoint.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"  # For HTTP
      - "4433:443"  # For HTTPS
    volumes:
      - ./backend:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/ssl/server-backend.crt:/etc/nginx/ssl/server-backend.crt
      - ./backend/ssl/server-backend.key:/etc/nginx/ssl/server-backend.key
      - ./frontend/ssl/server-frontend.crt:/etc/nginx/ssl/server-frontend.crt
      - ./frontend/ssl/server-frontend.key:/etc/nginx/ssl/server-frontend.key
      - ./backend/ssl:/etc/ssl/certs
      - ./backend/ssl/server.crt:/etc/ssl/certs/server.crt
      - ./backend/ssl/server.key:/etc/ssl/private/server.key
    networks:
      - symfony-angular-network
    depends_on:
      - symfony

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"  # Ensure you map the correct port
    networks:
      - symfony-angular-network
    extra_hosts:
      - "iba:127.0.0.1"  # Map custom hostname to localhost

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: zm_32
      MYSQL_DATABASE: zm_32
      MYSQL_USER: zm_32
      MYSQL_PASSWORD: zm_32
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-angular-network
    ports:
      - "3306:3306"  # Ensure this line exists
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database", "-u", "zm_32", "-pzm_32"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  symfony-angular-network:
    driver: bridge

volumes:
  db_data:
