version: '3.8'

services:
  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - symfony_code:/var/www/symfony
    environment:
      DATABASE_URL: mysql://zm_32:zm_32@database:3306/zm_32
      APP_ENV: prod
      APP_DEBUG: 0
    networks:
      - symfony-angular-network
    depends_on:
      database:
        condition: service_healthy
    entrypoint: /usr/local/bin/entrypoint.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "8000:80"  # For HTTP
      - "4433:443"  # For HTTPS
    volumes:
      - symfony_code:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/ssl:/etc/nginx/ssl  # Use a single mount for SSL
      - angular_dist:/var/www/angular/dist  # Angular build output
    networks:
      - symfony-angular-network
    depends_on:
      - symfony

  nginx-angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile-nginx-angular
    ports:
      - "8001:80"  # For Angular app
      - "4200:443"  # For Angular app
    volumes:
      - angular_dist:/var/www/angular/dist
      - ./frontend/ssl:/etc/nginx/ssl  # Use a single mount for SSL
    networks:
      - symfony-angular-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    volumes:
      - symfony_code:/var/www/symfony
      - ./var/log:/var/log
    networks:
      - symfony-angular-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: zm_32
      MYSQL_DATABASE: zm_32
      MYSQL_USER: zm_32
      MYSQL_PASSWORD: zm_32
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-angular-network
    ports:
      - "3306:3306"  # Ensure this line exists
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database", "-u", "zm_32", "-pzm_32"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  symfony-angular-network:
    driver: host

volumes:
  db_data:
  symfony_code:
  angular_dist:
