version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - symfony-angular-network

  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    networks:
      - symfony-angular-network

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    networks:
      - symfony-angular-network

networks:
  symfony-angular-network:
    driver: bridge
