# Use the official lightweight Nginx image
FROM nginx:alpine

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

RUN rm /etc/nginx/conf.d/default.conf

# Optional: Copy any static assets if needed
# COPY /path/to/static/assets /usr/share/nginx/html/assets

# Expose HTTP and HTTPS ports (optional, since defined in docker-compose)
EXPOSE 80 443
