# Use the official lightweight Nginx image
FROM nginx:alpine


#RUN apt-get update && apt-get install -y vim nano && apt-get clean
#RUN docker-php-ext-install pdo pdo_mysql

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

COPY php-fpm.conf /usr/local/etc/php-fpm.conf

RUN rm /etc/nginx/conf.d/default.conf

# Optional: Copy any static assets if needed
# COPY /path/to/static/assets /usr/share/nginx/html/assets

# Expose HTTP and HTTPS ports (optional, since defined in docker-compose)
EXPOSE 80
EXPOSE 443
