# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_origin: ['*']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'OPTIONS']
  paths:
    '^/':
      allow_origin: ['*']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'OPTIONS']