nelmio_cors:
  defaults:
    allow_origin: ['https://iba.local.de:4200']  # Change this to match your Angular frontend URL
    allow_credentials: false
    allow_headers: ['content-type', 'authorization']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']  # Correct the OPTIONS method here
    expose_headers: []
    max_age: 3600
  paths:
    '^/':  # This allows CORS for all routes; adjust as needed
      allow_origin: ['https://iba.local.de:4200']  # Ensure this matches your frontend URL
