index:
    path: /materialliste
    controller: App\Controller\IndexController::getmaterialliste

login_check:
    path: /login_check
    options:
        expose: true

app_login_check:
    path: /app/login_check
    options:
        expose: true