on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to My Local Server
        run: |
          scp -o StrictHostKeyChecking=no ./deploy.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/app
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "chmod +x deploy.sh && ./deploy.sh"
