name: Hourly Deploy

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose-prod.yml up -d --build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy with SCP
        run: |
          scp -r ./backend/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/symfony/
          scp -r ./frontend/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/angular/dist/
