name: Hourly Deploy

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes
        id: check_changes  # Adding an ID for the step
        run: |
          git fetch origin main
          if [ $(git rev-parse HEAD) != $(git rev-parse origin/main) ]; then
            echo "true" > changes.txt
          else
            echo "false" > changes.txt
          fi

      - name: Copy files via SSH
        if: steps.check_changes.outputs.changes == 'true'  # Conditional step
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "."
          target: "~/app"

      - name: Deploy via SSH
        if: steps.check_changes.outputs.changes == 'true'  # Conditional step
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/app
            docker-compose -f docker-compose-prod.yml down
            docker-compose -f docker-compose-prod.yml up --build -d

      - name: No changes detected
        if: steps.check_changes.outputs.changes == 'false'  # Conditional step
        run: echo "No changes detected."
