name: Hourly Deploy

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes
        run: |
          git fetch origin main
          if [ $(git rev-parse HEAD) != $(git rev-parse origin/main) ]; then
            echo "Changes detected, deploying..."
            # Add your deployment steps here
            # Example:
            uses: appleboy/scp-action@v0.1.3
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              passphrase: ${{ secrets.SSH_PASSPHRASE }}  
              source: "."
              target: "~/app"
          
            uses: appleboy/ssh-action@v0.1.6
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              passphrase: ${{ secrets.SSH_PASSPHRASE }}  
              script: |
                cd ~/app
                docker-compose -f docker-compose-prod.yml down
                docker-compose -f docker-compose-prod.yml up --build -d
          else
            echo "No changes detected."
          fi
